### ISSUE TITLE
There is no way to know reason of `Per second limit reached` error

### ISSUE THREAD

**Issue by k2m30** [piplcom/piplapis-ruby#7]
According to [documentation](https://pipl.com/dev/reference/#rate-limiting-information) all useful information is in response header, not body.

> **For your convenience**, we are showing limit information as HTTP response headers

I am not sure, who is that UX genius, but it is definitely **not convenient**.

> /home/deployer/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/piplapis-ruby-5.0.2/lib/pipl/client.rb:157:in `do_send': Per second limit reached. (Pipl::Client::APIError)

Corresponding method doesn't use headers to raise an error.

``` ruby
def do_send(http, req)
  response = http.request(req)
  if response.is_a? Net::HTTPSuccess
    SearchResponse.from_json(response.body)
  else
    begin
        err = Pipl::Client::APIError.from_json(response.body)
    rescue
        err = Pipl::Client::APIError.new response.message, response.code
    end
      raise err
  end
end
```

If there any way to meet 20 request per second limit using suggested approach?

``` ruby
thread = Pipl::client.search email: 'clark.kent@example.com', async: true do |resp|
  puts resp[:response] or resp[:error]
end
do_other_things()
```

**Comment by edoshor** [comment]
I totally agree. We've finally added the quota and throttle headers to both SearchResponse and APIError. Check out latest version (5.0.3) hope it helps.

Making sure queries are not throttled at all while maximizing the utilization of your key limits is not deterministic. Let's say your key has a 20 QPS limit and you send exactly 20 requests per second. Then due to network issues our servers might see more than 20 requests arriving at the same second, thus throttling some of them.

You can send about 70%-80% of your limits each second. So for a 20 QPS limit you could send 15 requests each second. It will increase the chances they won't get throttled. Two more points I would consider are:
- Some responses are sub-second quick (Errors, no results, etc...)
- You can resend throttled requests

Anyhow, stay tune since we plan some changes to the way quota and throttled are handled which might be interesting for you.
